services:
  app:
    build: .
    command: sh -c "npm run test:cov"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/vehicles-test
    networks:
      - app-network
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
